### ISSUE TITLE
Command "configure" is not defined.

### ISSUE THREAD

**Issue by andrefelipe18** [laradumps/laradumps-core#24]
This error 
![image](https://github.com/laradumps/laradumps-core/assets/96439642/ee542be2-90dc-4407-8c24-7c302210a55d)

But when using ./vendor/bin/laradumps init
![image](https://github.com/laradumps/laradumps-core/assets/96439642/c27364ab-1a0c-4ea3-a181-fe34ec3db53d)

**Comment by luanfreitasdev** [comment]
Hello!. This command was deprecated and became available in the previous version. In the new version, there is only an init
