### ISSUE TITLE
rewrite appBasePath function

### ISSUE THREAD

**Issue by emanuellopes** [laradumps/laradumps-core#7]
Hi, I'm trying create a new package to support wordpress functionalities, but I've some issues with the laradumps/laradumps-core package.

On Wordpress the function appBasepath, can have the following values:

- /var/www/html
- /var/www/html/wp-admin

With this issue I need to update the code manually and change the .env config directory to avoid duplicate file for both folders.

I started  a package but I'm unable to override this function on my package.

```php
if (!function_exists('appBasePath')) {
    function appBasePath(): string
    {
        $basePath = rtrim(strval(getcwd()), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        if (str_contains($basePath, 'public')) {
            $basePath = str_replace('public' . DIRECTORY_SEPARATOR, '', $basePath);
        }

        return $basePath;
    }
}
```

My idea is replacing that function by this:
```php
function appBasePath(): string
    {
       // this will allow developers, choose where the .env will stay.
        return apply_filters('wordpressdumps/appBasePath', get_stylesheet_directory());
    }
```

I've a solution, but is not perfect...

for example in your function, you can use something like
```php
function appBasePath(): string
{
    $basePath = rtrim(strval(getcwd()), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

    if(file_exists($basePath . '/.env')) {
        return $basePath;
    }

    // upp one level
    $basePath = rtrim(dirname(getcwd()), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

    if(file_exists($basePath . '/.env')) {
        return $basePath;
    }

    // upp two level
    return rtrim(dirname(getcwd(), 2), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
}
```

or moving the function appBasePath to Laradump class and in there place I will be able to override that function extending your base class.

**Comment by luanfreitasdev** [comment]
Hello @emanuellopes. Could you send a pull request to update the function? The core idea is exactly to create forks for other types of frameworks and take advantage of some existing resources. thank you

**Comment by emanuellopes** [comment]
My modifications to update our function I guess will not support everything.

**Comment by luanfreitasdev** [comment]
Sorry for the delay here. LaraDumps Core was recently refactored in version 2.0, if you're still willing to submit a PR, I'd be grateful.

Thanks
