### ISSUE TITLE
WordPress Dumps package

### ISSUE THREAD

**Issue by emanuellopes** [laradumps/laradumps-core#8]
Hi, I've created a package to support wordpress websites, but I was unable to use the current code from Laradump core, because the functions.php gfile.

So, I've forked your project and used as a library in my project. 

I leave here the link for project, but my idea is avoiding my fork.
https://github.com/emanuellopes/wordpressdumps

**Comment by luanfreitasdev** [comment]
Sorry for the delay here. LaraDumps Core was recently refactored in version 2.0, if you're still willing to submit a PR, I'd be grateful.

Thanks
